<Project Sdk="Remora.Sdk">
    <PropertyGroup>
        <LibraryFrameworks>net462;netstandard2.0;netstandard2.1;net8.0;net10.0</LibraryFrameworks>
    </PropertyGroup>

    <PropertyGroup>
        <VersionPrefix>9.0.0</VersionPrefix>
        <Description>
            A basic implementation of a descriptive algebraic data type for C#.
        </Description>
        <PackageReleaseNotes>
            Upgrade target framework and nuget packages.
            Update net461 target to net462 since System.ValueTuple no longer works with net461.
        </PackageReleaseNotes>
        <PackageTags>$(PackageTags);algebraic datatype;result;results</PackageTags>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net462'">
        <PackageReference Include="System.ValueTuple" />
    </ItemGroup>
</Project>